# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 89043167b3045bd8d561c2eb823809a17abf2e1f8b2c4f91f8536f376cee472765974d226603cfd0ca777347f28dc6914fdff3b0dcd4c7818a52f08e222f8b93

test:
  secret_key_base: e1be796630fd7c9dbf40dfe59c538282fd2ad1a71e12508a492953e55a8f76e603eb07c4234b4a07892de50549f8b483ead7a59e6e1e8c6367dfb17608c21e85

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
